import {
  LOADING,
  SAVE_TASK,
  SAVE_TASK_ERROR,
  GET_TASKS,
  GET_TASKS_ERROR,
  MODIFY_TASK,
  MODIFY_TASK_ERROR,
  DELETE_TASK,
  DELETE_TASK_ERROR,
  DELETE_SECTION,
  DELETE_SECTION_ERROR,
  GET_SECTIONS,
  GET_SECTIONS_ERROR,
  MODIFY_SECTION,
  MODIFY_SECTION_ERROR,
  SAVE_SECTION,
  SAVE_SECTION_ERROR
} from './services';

import {
  SMALL,
  MID,
  BIG,
  LIMIT
} from './time'

export {
  LOADING,
  SAVE_TASK,
  SAVE_TASK_ERROR,
  GET_TASKS,
  GET_TASKS_ERROR,
  MODIFY_TASK,
  MODIFY_TASK_ERROR,
  DELETE_TASK,
  DELETE_TASK_ERROR,
  DELETE_SECTION,
  DELETE_SECTION_ERROR,
  GET_SECTIONS,
  GET_SECTIONS_ERROR,
  MODIFY_SECTION,
  MODIFY_SECTION_ERROR,
  SAVE_SECTION,
  SAVE_SECTION_ERROR,

  SMALL,
  MID,
  BIG,
  LIMIT
}
