/** LOADER **/
export const LOADING = 'LOADING';

/** TASK **/
export const SAVE_TASK = 'SAVE_TASKS';
export const SAVE_TASK_ERROR = 'SAVE_TASK_ERROR';
export const MODIFY_TASK = 'MODIFY_TASKS';
export const MODIFY_TASK_ERROR = 'MODIFY_TASK_ERROR';
export const DELETE_TASK = 'DELETE_TASKS';
export const DELETE_TASK_ERROR = 'DELETE_TASK_ERROR';
export const GET_TASKS = 'GET_TASKS';
export const GET_TASKS_ERROR = 'GET_TASKS_ERROR';

/** SECTION **/
export const SAVE_SECTION = 'SAVE_SECTIONS';
export const SAVE_SECTION_ERROR = 'SAVE_SECTION_ERROR';
export const MODIFY_SECTION = 'MODIFY_SECTIONS';
export const MODIFY_SECTION_ERROR = 'MODIFY_SECTION_ERROR';
export const DELETE_SECTION = 'DELETE_SECTIONS';
export const DELETE_SECTION_ERROR = 'DELETE_SECTION_ERROR';
export const GET_SECTIONS = 'GET_SECTIONS';
export const GET_SECTIONS_ERROR = 'GET_SECTIONS_ERROR';
